# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        
      - name: Build project
        run: npm i && npm run build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: dist/
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
          
          
        
    
